### ISSUE TITLE
Include integration test to capture requirement to support hosted githubs

### ISSUE THREAD

**Issue by zpratt** [form8ion/lift#1165]

**Comment by travi** [comment]
as discussed offline, handling interactions with git with the mocked filesystem can be a bit tricky. in other projects i've had to resort to some alternative setup steps like 

https://github.com/form8ion/project/blob/3f89ad9f18f5b5f4b825baf47b9299d5d51f5af9/test/integration/features/step_definitions/vcs/git-steps.js#L20-L23

**Comment by travi** [comment]
i'm seeing an issue locally after this change when this behavior isnt stubbed and it uses the origin of my local clone:

```
Error: URL parsing failed.
    at throwErr (/path/to/form8ion/lift/node_modules/parse-url/dist/index.js:294:21)
    at parseUrl (/path/to/development/form8ion/lift/node_modules/parse-url/dist/index.js:331:13)
    at gitUp (/path/to/development/form8ion/lift/node_modules/git-up/lib/index.js:29:18)
    at gitUrlParse (/path/to/development/form8ion/lift/node_modules/git-url-parse/lib/index.js:48:19)
    at determineExistingHostDetails (file:///path/to/development/form8ion/lift/lib/index.js:29:52)
    at async lift (file:///path/to/development/form8ion/lift/lib/index.js:39:15)
    at async file:///path/to/development/form8ion/lift/remark-usage-example-lpcv88_wvisnxfcruili3.js:22:3 {
  subject_url: 'git@github.com:form8ion/lift.git\n'
}
```

i'm working on added the appropriate stubs and returning an https url instead of ssh seems to work fine. this is making me worry that there may be an issue when used against real local clones

**Comment by travi** [comment]
update: returning an ssh url from the stub also seems to work. i'm betting that `\n` is significant. i wonder if `simple-git` is returning the origin with a trailing new line for some reason and GitParseUrl isnt prepared to handle this.

i'm also wondering why this didnt fail locally or on ci before this was merged 🤔

**Comment by travi** [comment]
> i'm betting that `\n` is significant

if i do add a `\n` to the stub return value, i've confirmed that it fails in the same way. just need to confirm what is introducing that newline

**Comment by travi** [comment]
pushed stubbing of the remote parsing steps in https://github.com/form8ion/lift/commit/0fa8b86a99865d44a797731be06eb50ace125ed2

did not yet further investigate where the `\n` is coming from for my local clone
